### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by kernie66** [vectronic/homebridge-ping-hosts#10]
Hi, I like this plugin but I would like it to start in an error-free state. Otherwise when I set a long interval, the contact in HomeKit will be open until the interval has passed and the first ping is sent. This can give false triggers for my automations when Homebridge is restarted. 

Suggestions:

* Either the start state could be set to closed at init of the accessory,
* Or a user selectable start state could be set in the configuration.
* Another way could be to initiate a ping at start. I modified the code to do a setImmediate() before the setInterval() line. It works for me, but I don't know if it has any side effects.

Thanks,
Kenneth

**Comment by kernie66** [comment]
Sorry, I saw now that this has already been addressed in the pull request.

**Comment by vectronic** [comment]
See if the new version's supported config works for you: https://www.npmjs.com/package/@vectronic/homebridge-ping-hosts

It now has support for two new properties:

* "startup_as_failed": defaults to true
* "closed_on_success": defaults to true

I did think about doing a setImmediate() but didn't go for it... no real reason... might introduce some issues if a whole lot of other systems are starting up at the same time... but unlikely.

**Comment by kernie66** [comment]
Thanks, this covers my needs. Very quick response 👍👍
