### ISSUE TITLE
Enhancement Request Configurable device

### ISSUE THREAD

**Issue by mbierman** [vectronic/homebridge-ping-hosts#17]
Any chance you would consider making the device configurable so it could be 
- Contact
- Light
- Motion

**Comment by vectronic** [comment]
I don't think light or motion really make sense for a network ping test....?

**Comment by mbierman** [comment]
So if you want a simple view, "is it on or off" I could see light making sense. Letting the user choose the sensor type is done in many plugins and is nice. 

Your current contact makes sense too. And I like that you allow it to be flipped although at first I kind of had it backward in my head because the iconography for contact in Homebridge looks like it is "off" when it is found. (because I was thinking of it as a light, not the closed circuit of a contact sensor.) So what you have is 100% this would just allow the user to have a light on if the device is found and light off if the device is not found.

**Comment by vectronic** [comment]
Ahh I see. I have always used this as a test of whether Internet access is up. Therefore the contact sensor. I had never considered using it as a test to see if a device on the network is responding i.e. a light or TV etc.

Does https://github.com/marcveens/homebridge-device-alive#readme cover your use case?

**Comment by mbierman** [comment]
Not really because of the device type as described https://github.com/vectronic/homebridge-ping-hosts/issues/18#issuecomment-1167201813

**Comment by vectronic** [comment]
Updated here https://github.com/vectronic/homebridge-ping-hosts

I won't be able to test until the weekend and will then publish a release...

**Comment by vectronic** [comment]
The published version 3.1.4 seems to do this correctly. Feel free to open another ticket if you find an issue.
