### ISSUE TITLE
Not able to add with hb-service

### ISSUE THREAD

**Issue by Rahulsharma0810** [vectronic/homebridge-ping-hosts#27]
root@some-kube-node-1-01:/var/lib/homebridge $ hb-service add homebridge-ping-hosts
ℹ CMD: npm --prefix "/var/lib/homebridge" add homebridge-ping-hosts@latest
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-ping-hosts - Not found
npm ERR! 404 
npm ERR! 404  'homebridge-ping-hosts@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-09-15T07_56_18_543Z-debug-0.log
✖ Plugin installation failed.

Could you add this, so this plugin can be installed with container startup scripts?

**Comment by vectronic** [comment]
It is available as:

@vectronic/homebridge-ping-hosts

here:

https://www.npmjs.com/package/@vectronic/homebridge-ping-hosts
