### ISSUE TITLE
Guidance on how to disable failure logging

### ISSUE THREAD

**Issue by colereynolds** [vectronic/homebridge-ping-hosts#28]
Is there a way to disable logging on failures? I get the example below at every interval and it's filing up my homebridge log.

`[PingHosts] [Gaming Laptop] response error: Error: not alive for 192.168.7.8`

**Comment by spalda8** [comment]
Same problem, I have got full log now.
Please add option to turn it off, or turn it off as before.
Love your script.
Thank you

**Comment by vectronic** [comment]
Give me a few days and I will look at it.

**Comment by colereynolds** [comment]
@vectronic Thank you!
