### ISSUE TITLE
hostname

### ISSUE THREAD

**Issue by asyba** [vectronic/homebridge-ping-hosts#29]
why no hostname?
like www.google.com

**Comment by vectronic** [comment]
Good question. Looking at the underlying ping library it does support host names. Have you tried to set one for the ipv4 value and see if it works?

**Comment by asyba** [comment]
> Good question. Looking at the underlying ping library it does support host names. Have you tried to set one for the ipv4 value and see if it works?

I did't try.
I just tried, at least no error on homebridge logs for www.google.com
is there a setting to enable debug logs and see the ping to that address?

**Comment by vectronic** [comment]
I think you run homebridge -D for debug logs.

**Comment by asyba** [comment]
@vectronic it works for host name, you should update the Readme. 
also your code base on https://github.com/jsworks/homebridge-ping-hosts that supports hostanames

**Comment by vectronic** [comment]
@asyba thanks - I have updated the readme.
