### ISSUE TITLE
Operation not permitted at new Socket

### ISSUE THREAD

**Issue by reziCCAA** [vectronic/homebridge-ping-hosts#5]
I have installed this plugin to ping my TV. First it worked as expected. But for a few days now the sensor stays open although the TV is online. 
Ping via ssh to the respective IP is successful.
I also updated the Pi and re-installed the plugin itself. 
Logs attached.![image](https://user-images.githubusercontent.com/39808577/91620506-76728300-e990-11ea-857b-bf86ccf0b4e5.jpeg)

**Comment by vectronic** [comment]
Check the note on « operation not permitted » in the readme.md in the root of the project source. Looks like your permissions for the node process need to be modified.

**Comment by reziCCAA** [comment]
Sorry for not reading it before. Then the last updates might be the reason. 
Anyway, now it works again!
Thanks!
