### ISSUE TITLE
Different HomeKit sensor

### ISSUE THREAD

**Issue by agneevX** [vectronic/homebridge-ping-hosts#9]
Maybe use another HomeKit sensor like Occupancy?

Currently, with the contact sensor, it's hard to know whether the host is up or not.

**Comment by vectronic** [comment]
Personally I don’t agree with this. Ability to ping an IP address seems to me much more related to a contact sensor than to an occupancy sensor. 

If you want this change I’d be happy if  you submit a PR which provides the ability to configure whether the plugin exposes a contact sensor or occupancy sensor.
